version: '3.9'
services:
  app:
    image: nbc-rag-be
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app
      - type: bind
        target: /usr/src/app/node_modules
    environment:
      - NODE_ENV=PROD
